nspcc-dev/s3-tests

s3tests_boto3/functional/test_s3.py
Now this test processes an error in a response.
=> Fix test_continuationtoken_empty

s3tests_boto3/functional/test_s3.py
Added attributes to test_bucket_listv2_continuationtoken_empty_neofs_s3
=> Add attributes to continuationtoken_empty_neofs_s3

s3tests_boto3/functional/test_s3.py
Signed-off-by: Angira Kekteeva <kira@nspcc.ru>
=> [#6] Add attr 'multipart' to missed test

NEOFS_README.md, bootstrap
=> Arch bootstrap and docs

s3tests_boto3/functional/test_s3_neofs.py
=> [#10] Add bucket workflow test

s3tests_boto3/functional/test_s3_neofs.py
=> [#13] Add object workflow test

s3tests_boto3/functional/test_s3_neofs.py
=> [#14] Add list objects workflow test

s3tests_boto3/functional/test_s3_neofs.py
=> [#15] Add multipart workflow test

s3tests_boto3/functional/test_s3_neofs.py
=> [#16] Add versioning workflow test

s3tests_boto3/functional/test_s3_neofs.py
=> [#17] Add tagging workflow tests

requirements.txt, s3tests_boto3/functional/test_s3_neofs.py, setup.py
Update boto3 to 1.24.4
close #18
=> [#18] Add object attributes test

NEOFS_README.md
=> [#29] Fix ubuntu prerequisites guide

.github/workflows/dco.yml
=> workflows: add standard DCO check

s3tests_boto3/functional/test_s3.py
As a result of the review under https://github.com/nspcc-dev/neofs-s3-gw/pull/809 added sanity marks into tests
=> Marked tests with sanity attr

bootstrap
Added zip package to bootstrap package list to archive logs for #41
=> Added zip package. Part of #41

s3tests_boto3/functional/test_s3.py
Adjusted sanity tests list.
Removed tests are failing. Looks like, for now, it's better to have green sanity runs. And on the next stage investigate every test fail.
=> Removed some tests from sanity list

s3tests_boto3/functional/test_s3_neofs.py
1. Update skip marks with corresponding issues
2. Fix requests verify parameter usage
3. Unskip working tests
=> tests: actualize test_s3_neofs

s3tests_boto3/functional/test_s3.py
=> tests: actualize skips for post object tests

requirements.txt, s3tests_boto3/functional/test_s3.py
botocore version update was validated here - https://github.com/evgeniiz321/neofs-s3-gw/actions/runs/6673779454/job/18139813030?pr=2, no issues found.
=> tests: update skips and requirements

s3tests_boto3/functional/__init__.py, s3tests_boto3/functional/test_s3.py, s3tests_boto3/functional/test_s3_neofs.py, s3tests_boto3/functional/utils.py
Followed @evgeniiz321 review advice and implemented client methods overload with allure wraps.
=> Allure steps for s3-tests. Fixes #39

conftest.py
Otherwise it's incompatible with the current code.
=> neofs-testcases: update revision to current ~0.45.0
